init:
  - appveyor version
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD

build_script:
  - sh: echo "this is a test1" >foo1
  - sh: echo "this is a test2" >foo2

artifacts:
  - path: foo1
  - path: foo2

test: off

deploy_script: 
  - ps: | 
          foreach ($artifactName in $artifacts.keys) { 
            Write-Host $artifactName 
            Write-Host $artifacts[$artifactName].path 
          }
  - sh: sudo journalctl -u appveyor-build-agent.service  --no-pager
  
