init:
  - appveyor version
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD

build_script:
  - sh: echo "this is a test1" >foo1
  - sh: echo "this is a test2" >foo2

artifacts:
  - path: foo1
  - path: foo2

test: off

deploy_script: 
  - ps: | 
          foreach ($artifactName in $artifacts.keys) { 
            Write-Host $artifactName 
            Write-Host $artifacts[$artifactName].path 
          }
          $artifacts.GetType()
          if ($artifacts.count -eq 2) {
              Write-Host "2 artifacts enlisted"
          } else {
              Write-Host "artifacts variable does not contain 2 objects" -foreground red
              exit 1
          }
  - sh: sudo journalctl -u appveyor-build-agent.service  --no-pager > buildagent.log
  - appveyor PushArtifact buildagent.log 
  
